
# **Business Understanding**

#### **Apple Global Product Sales Dataset**

11,500 synthetic sales transactions for iPhone, iPad, Mac, Apple Watch, AirPods, and Accessories across 47 countries, 514+ cities, sorted by Country → City → Date (2022 – 2024).

This dataset simulates a realistic global sales ledger for Apple Inc. products.It covers city-level transactions across multiple continents, currencies, sales channels,and customer demographics — ideal for retail analytics, market segmentation, price analysis, time-series forecasting, and geographic visualisation.

source: [Data set source](https://www.kaggle.com/datasets/ashyou09/apple-global-product-sales-dataset)

## **Data Understanding**

- head and tail (printing out the first 5 or few entries and the last entries)
- shape (dimensions)
- columns
- datatypes
- info
- describe numerical (descriptive)
- describe categroical

#### Load libraries

In [6]:
import pandas as pd
import matplotlib.pyplot  as plt
import numpy as np
pd.set_option('display.max_columns', None)  # Show all columns

#### Load data

In [3]:
apple_df = pd.read_csv("data/apple_global_sales_dataset.csv")

#### Get a glimpse of the data

In [9]:
apple_df.head(10)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,NaN,Starlight,159.27,7,1,148.12,148.12,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,NaN,Black,29.99,15,5,25.49,127.45,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,NaN,Titanium,293.92,0,4,293.92,1175.68,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,1932.77,0,2,1932.77,3865.54,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,NaN,Midnight,755.44,5,3,717.67,2153.01,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept
5,APPL-00000006,2022-07-31,2022,Q3,July,Argentina,South America,Buenos Aires,Magic Keyboard,Accessories,NaN,Silver,103.02,0,3,103.02,309.06,ARS,907.0,280317.42,Apple Store,Cash,Education,55+,NaN,4.9,Kept
6,APPL-00000007,2022-08-01,2022,Q3,August,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,2003.70,3,1,1943.59,1943.59,ARS,907.0,1762836.13,Apple Store,Gift Card,Government,35–44,NaN,3.6,Kept
7,APPL-00000008,2022-08-04,2022,Q3,August,Argentina,South America,Buenos Aires,iPhone 15 Pro Max,iPhone,64 GB,Black,1228.96,15,8,1044.62,8356.96,ARS,907.0,7579762.72,Carrier Store,Gift Card,Education,25–34,iOS 16,4.7,Kept
8,APPL-00000009,2023-01-14,2023,Q1,January,Argentina,South America,Buenos Aires,Apple TV 4K (3rd Gen),Accessories,NaN,White,122.99,0,8,122.99,983.92,ARS,907.0,892415.44,Authorized Reseller,Gift Card,Government,18–24,NaN,4.7,Kept
9,APPL-00000010,2023-01-26,2023,Q1,January,Argentina,South America,Buenos Aires,iPad Mini (6th Gen),iPad,128 GB,Starlight,520.05,0,1,520.05,520.05,ARS,907.0,471685.35,Third-Party Retailer,Apple Pay,Business,25–34,NaN,3.6,Kept

In [10]:
apple_df.tail(10)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
11490,APPL-00011491,2023-11-24,2023,Q4,November,Vietnam,Asia,Nha Trang,Magic Trackpad,Accessories,NaN,Silver,138.29,0,5,138.29,691.45,VND,24500.0,16940525.0,Carrier Store,Debit Card,Government,18–24,NaN,NaN,Kept
11491,APPL-00011492,2023-11-24,2023,Q4,November,Vietnam,Asia,Nha Trang,iPhone 14 Pro,iPhone,64 GB,Silver,832.10,10,2,748.89,1497.78,VND,24500.0,36695610.0,Corporate / B2B,Gift Card,Individual,18–24,Other,3.0,Kept
11492,APPL-00011493,2023-12-19,2023,Q4,December,Vietnam,Asia,Nha Trang,Magic Mouse,Accessories,NaN,Black,82.20,3,2,79.73,159.46,VND,24500.0,3906770.0,Carrier Store,Gift Card,Government,18–24,NaN,NaN,Kept
11493,APPL-00011494,2023-12-29,2023,Q4,December,Vietnam,Asia,Nha Trang,MacBook Pro 16-inch (M3 Pro),Mac,256 GB SSD,Starlight,2666.18,0,1,2666.18,2666.18,VND,24500.0,65321410.0,Corporate / B2B,Credit Card,Business,55+,NaN,3.6,Kept
11494,APPL-00011495,2024-01-07,2024,Q1,January,Vietnam,Asia,Nha Trang,MacBook Pro 16-inch (M3 Pro),Mac,2 TB SSD,Silver,2425.12,0,2,2425.12,4850.24,VND,24500.0,118830880.0,Online (Apple.com),Credit Card,Business,18–24,NaN,NaN,Kept
11495,APPL-00011496,2024-02-08,2024,Q1,February,Vietnam,Asia,Nha Trang,Apple Watch Series 9,Apple Watch,NaN,Natural,420.53,5,2,399.50,799.00,VND,24500.0,19575500.0,Third-Party Retailer,Gift Card,Individual,18–24,NaN,4.0,Kept
11496,APPL-00011497,2024-02-15,2024,Q1,February,Vietnam,Asia,Nha Trang,Mac Pro (M2 Ultra),Mac,256 GB SSD,Midnight,7302.60,7,1,6791.42,6791.42,VND,24500.0,166389790.0,Corporate / B2B,Gift Card,Education,45–54,NaN,4.9,Kept
11497,APPL-00011498,2024-08-28,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone 15,iPhone,128 GB,Deep Purple,759.97,7,5,706.77,3533.85,VND,24500.0,86579325.0,Authorized Reseller,Debit Card,Government,35–44,iOS 16,3.8,Kept
11498,APPL-00011499,2024-08-31,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone SE (3rd Gen),iPhone,512 GB,Black,438.99,0,1,438.99,438.99,VND,24500.0,10755255.0,Apple Store,EMI / Installment,Education,55+,iOS 17,NaN,Kept
11499,APPL-00011500,2024-10-10,2024,Q4,October,Vietnam,Asia,Nha Trang,iPhone 15 Pro Max,iPhone,512 GB,Silver,1271.57,7,1,1182.56,1182.56,VND,24500.0,28972720.0,Online (Apple.com),EMI / Installment,Individual,35–44,Other,3.6,Kept

In [13]:
rows, columns =  apple_df.shape
output = f"ROWS: {rows} || COLUMNS: {columns}"
print(output)

ROWS: 11500 || COLUMNS: 27

Insight: 
- Dataset has 11500 records and 27 features

#### Descriptive Stats

- MCTs -> measures os central tendency (Mean, Median, Mode)
- MoV -> measures of variation (range, IQR, percentile, quartiles,variance , standard deviation )

In [14]:
apple_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 11500 non-null  str
 1   sale_date               11500 non-null  str
 2   year                    11500 non-null  int64
 3   quarter                 11500 non-null  str
 4   month                   11500 non-null  str
 5   country                 11500 non-null  str
 6   region                  11500 non-null  str
 7   city                    11500 non-null  str
 8   product_name            11500 non-null  str
 9   category                11500 non-null  str
 10  storage                 6696 non-null   str
 11  color                   11500 non-null  str
 12  unit_price_usd          11500 non-null  float64
 13  discount_pct            11500 non-null  int64
 14  units_sold              11500 non-null  int64
 15  discounted_price_usd    11500 non-null  float64
 16  revenue_usd             11500 non-null  float64
 17  currency                11500 non-null  str
 18  fx_rate_to_usd          11500 non-null  float64
 19  revenue_local_currency  11500 non-null  float64
 20  sales_channel           11500 non-null  str
 21  payment_method          11500 non-null  str
 22  customer_segment        11500 non-null  str
 23  customer_age_group      11500 non-null  str
 24  previous_device_os      3444 non-null   str
 25  customer_rating         8140 non-null   float64
 26  return_status           11500 non-null  str
dtypes: float64(6), int64(3), str(18)
memory usage: 2.4 MB

In [16]:
apple_df.dtypes

sale_id                       str
sale_date                     str
year                        int64
quarter                       str
month                         str
country                       str
region                        str
city                          str
product_name                  str
category                      str
storage                       str
color                         str
unit_price_usd            float64
discount_pct                int64
units_sold                  int64
discounted_price_usd      float64
revenue_usd               float64
currency                      str
fx_rate_to_usd            float64
revenue_local_currency    float64
sales_channel                 str
payment_method                str
customer_segment              str
customer_age_group            str
previous_device_os            str
customer_rating           float64
return_status                 str
dtype: object

Insights: 
- A few columns in the dataset is composed of Null / empty values
- composed of  both categorical and numerical data

In [17]:
apple_df.describe() # get desciptive stats of numerical data

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,1.150000e+04,8140.000000
mean,2022.997304,807.851191,3.841565,2.023478,777.365478,1568.319065,1029.406647,1.464369e+06,4.000934
std,0.821747,1112.437595,4.783161,1.443599,1072.915122,2839.759822,4072.334957,9.941160e+06,0.575192
min,2022.000000,26.690000,0.000000,1.000000,22.730000,23.000000,0.790000,2.130000e+01,3.000000
25%,2022.000000,180.147500,0.000000,1.000000,178.297500,305.740000,0.920000,1.041693e+03,3.500000
50%,2023.000000,593.905000,2.000000,1.000000,573.420000,833.040000,7.240000,6.164160e+03,4.000000
75%,2024.000000,958.387500,7.000000,3.000000,928.567500,1748.360000,91.500000,7.471653e+04,4.500000
max,2024.000000,7551.010000,15.000000,8.000000,7551.010000,59529.520000,24500.000000,5.075175e+08,5.000000

Insights:

1. Year:
- it between 2022 and 2024, with 75% of the sales made below 2024 and 50% pf the sales were around 2023

In [18]:
apple_df.describe(include='object') # get desciptive stats of numerical data

/tmp/ipykernel_11207/1766351801.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  apple_df.describe(include='object') # get desciptive stats of numerical data

,sale_id,sale_date,quarter,month,country,region,city,product_name,category,storage,color,currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,return_status
count,11500,11500,11500,11500,11500,11500,11500,11500,11500,6696,11500,11500,11500,11500,11500,11500,3444,11500
unique,11500,1096,4,12,47,8,514,43,6,10,20,38,6,7,4,5,6,3
top,APPL-00000001,2022-07-31,Q4,March,Japan,Europe,Singapore,Apple Watch SE (2nd Gen),iPhone,64 GB,Silver,EUR,Online (Apple.com),Credit Card,Government,25–34,Android,Kept
freq,1,23,2922,1047,274,3898,237,312,3444,944,1690,2433,1940,1683,2892,2347,595,10143

Insights:
-