# **Business Understanding:**

Analyze  the Calls made in the company and try and finc out areas of improvement

**Data:**

[Data Source](https://www.kaggle.com/datasets/akash1vishwakarma/call-center-dataset)

#### **Load Libraries**

In [1]:
import matplotlib.pyplot as plt 
import pandas as pd 
import numpy as np 
import seaborn as sns 
import scipy as stats

#### **Load Data**

In [2]:
df = pd.read_excel('data/01 Call-Center-Dataset.xlsx')

# **Data Undestanding:**
- glimpse of the data(head, tail)
- shape(dimensions)
- columns
- information
- data type
- duplicates
- outliers
- null values
- descriptive stats (quantitative and qualitative)

#### **Glimpse of the data:**

In [3]:
df.head()

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
0,ID0001,Diane,2021-01-01,09:12:58,Contract related,Y,Y,109.0,00:02:23,3.0
1,ID0002,Becky,2021-01-01,09:12:58,Technical Support,Y,N,70.0,00:04:02,3.0
2,ID0003,Stewart,2021-01-01,09:47:31,Contract related,Y,Y,10.0,00:02:11,3.0
3,ID0004,Greg,2021-01-01,09:47:31,Contract related,Y,Y,53.0,00:00:37,2.0
4,ID0005,Becky,2021-01-01,10:00:29,Payment related,Y,Y,95.0,00:01:00,3.0

In [4]:
df.tail()

,Call Id,Agent,Date,Time,Topic,Answered (Y/N),Resolved,Speed of answer in seconds,AvgTalkDuration,Satisfaction rating
4995,ID4996,Jim,2021-03-31,16:37:55,Payment related,Y,Y,22.0,00:05:40,1.0
4996,ID4997,Diane,2021-03-31,16:45:07,Payment related,Y,Y,100.0,00:03:16,3.0
4997,ID4998,Diane,2021-03-31,16:53:46,Payment related,Y,Y,84.0,00:01:49,4.0
4998,ID4999,Jim,2021-03-31,17:02:24,Streaming,Y,Y,98.0,00:00:58,5.0
4999,ID5000,Diane,2021-03-31,17:39:50,Contract related,N,N,NaN,NaN,NaN

#### **Dimensions, columns & datatypes**

In [5]:
rows, columns = df.shape
output = f"Records: {rows} and Features: {columns}"
print(output)

Records: 5000 and Features: 10

In [6]:
df.columns

Index(['Call Id', 'Agent', 'Date', 'Time', 'Topic', 'Answered (Y/N)',
       'Resolved', 'Speed of answer in seconds', 'AvgTalkDuration',
       'Satisfaction rating'],
      dtype='str')

In [8]:
df.dtypes

Call Id                           str
Agent                             str
Date                              str
Time                           object
Topic                             str
Answered (Y/N)                    str
Resolved                          str
Speed of answer in seconds    float64
AvgTalkDuration                object
Satisfaction rating           float64
dtype: object

#### **Info, duplicates, outliers,null values**

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Call Id                     5000 non-null   str
 1   Agent                       5000 non-null   str
 2   Date                        5000 non-null   str
 3   Time                        5000 non-null   object
 4   Topic                       5000 non-null   str
 5   Answered (Y/N)              5000 non-null   str
 6   Resolved                    5000 non-null   str
 7   Speed of answer in seconds  4054 non-null   float64
 8   AvgTalkDuration             4054 non-null   object
 9   Satisfaction rating         4054 non-null   float64
dtypes: float64(2), object(2), str(6)
memory usage: 390.8+ KB

Insights: 
- we have missing values in the  Speed of answer in seconds, AvgTalkDuration and Satisfaction rating  features