# **Business Understanding**


## THE CLIMATE CHANGE 

<img src="https://ocw.mit.edu/courses/cms-631-data-storytelling-studio-climate-change-spring-2017/6a102252006ddb7f4bc6e80ad8e90199_cms-631s17.gif"     alt="Historical Temperature Change"     style="float: left; margin-right: 50px;width:300px;height:300px;" />


Climate change is one of the important issues that face the world in this technological era. The best proof of this situation is the historical temperature change (It is shown in left figure[⁴](https://ocw.mit.edu/courses/comparative-media-studies-writing/cms-631-data-storytelling-studio-climate-change-spring-2017/#)).  Our project investigates the reality of the increase in temperatures linked to industrial activities and the greenhouse effect. And before this investigation, the aim of this part enlight the significant sides of the temperature change data for each area. Before beginning the analysis, firstly, I want to figure out our problem, its cause and its effects in a short way. 
 
 #### What is Climate Change?
 
"_Climate change is a long-term change in the average weather patterns that have come to define Earth’s local, regional and global climates. Changes observed in Earth’s climate since the early 20th century are primarily driven by human activities, particularly fossil fuel burning, which increases heat-trapping greenhouse gas levels in Earth’s atmosphere, raising Earth’s average surface temperature. These human-produced temperature increases are commonly referred to as global warming._[⁵](https://climate.nasa.gov/resources/global-warming-vs-climate-change/)"
 
 ##### Causes
According to NASA, Water Vapour, Carbon dioxide(CO₂), Methane, Nitrous oxide, Chlorofluorocarbons(CFCs) contribute to the greenhouse effect. Over the last century, human activities have increased concentrations of this natural greenhouse.
 
 ##### Effects:

"_Global climate change has already had observable effects on the environment. Glaciers have shrunk, ice on rivers and lakes is breaking up earlier, plant and animal ranges have shifted, and trees are flowering sooner. Effects that scientists had predicted in the past would result from global climate change: loss of sea ice accelerated sea-level rise and longer, more intense heat waves._[⁶](https://climate.nasa.gov/effects/)"


[Reference](https://www.kaggle.com/code/sevgisarac/climate-change#Guiding-Questions)
[Data Source](https://www.fao.org/faostat/en/#data/ET)

#### **Load Libraries**

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

#### **Load Data**

In [3]:
climate_df = pd.read_csv("data/FAOSTAT_data_en_3-11-2026.csv")

# **Data Understanding**
- head...tail (glimpse of the data)
- shape/ dimensions
- columns
- info
- missing values
- outliers
- duplicates
- descriptive stats(numerical and categorical)
- basic visualizations

#### **Glimpse of the data**

In [4]:
climate_df.head(4)

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Months Code,Months,Year Code,Year,Unit,Value,Flag,Flag Description
0,ET,Temperature change on land,4,Afghanistan,7271,Temperature change,7001,January,2022,2022,°c,2.297,E,Estimated value
1,ET,Temperature change on land,4,Afghanistan,7271,Temperature change,7001,January,2023,2023,°c,-2.418,E,Estimated value
2,ET,Temperature change on land,4,Afghanistan,6078,Standard Deviation,7001,January,2022,2022,°c,1.964,E,Estimated value
3,ET,Temperature change on land,4,Afghanistan,6078,Standard Deviation,7001,January,2023,2023,°c,1.964,E,Estimated value

In [5]:
climate_df.tail(4)

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Months Code,Months,Year Code,Year,Unit,Value,Flag,Flag Description
16180,ET,Temperature change on land,716,Zimbabwe,7271,Temperature change,7020,Meteorological year,2022,2022,°c,0.494,E,Estimated value
16181,ET,Temperature change on land,716,Zimbabwe,7271,Temperature change,7020,Meteorological year,2023,2023,°c,1.009,E,Estimated value
16182,ET,Temperature change on land,716,Zimbabwe,6078,Standard Deviation,7020,Meteorological year,2022,2022,°c,0.311,E,Estimated value
16183,ET,Temperature change on land,716,Zimbabwe,6078,Standard Deviation,7020,Meteorological year,2023,2023,°c,0.311,E,Estimated value

#### **Dimensions**

In [7]:
records,features = climate_df.shape
output = f"Data set is composed of {records} records and {features} features"
print(output)

Data set is composed of 16184 records and 14 features

#### **info, data types, columns**

In [8]:
climate_df.info

<bound method DataFrame.info of       Domain Code                      Domain  Area Code (M49)         Area  \
0              ET  Temperature change on land                4  Afghanistan
1              ET  Temperature change on land                4  Afghanistan
2              ET  Temperature change on land                4  Afghanistan
3              ET  Temperature change on land                4  Afghanistan
4              ET  Temperature change on land                4  Afghanistan
...           ...                         ...              ...          ...
16179          ET  Temperature change on land              716     Zimbabwe
16180          ET  Temperature change on land              716     Zimbabwe
16181          ET  Temperature change on land              716     Zimbabwe
16182          ET  Temperature change on land              716     Zimbabwe
16183          ET  Temperature change on land              716     Zimbabwe

       Element Code             Element  Months Code               Months  \
0              7271  Temperature change         7001              January
1              7271  Temperature change         7001              January
2              6078  Standard Deviation         7001              January
3              6078  Standard Deviation         7001              January
4              7271  Temperature change         7002             February
...             ...                 ...          ...                  ...
16179          6078  Standard Deviation         7019          Sep–Oct–Nov
16180          7271  Temperature change         7020  Meteorological year
16181          7271  Temperature change         7020  Meteorological year
16182          6078  Standard Deviation         7020  Meteorological year
16183          6078  Standard Deviation         7020  Meteorological year

       Year Code  Year Unit  Value Flag Flag Description
0           2022  2022   °c  2.297    E  Estimated value
1           2023  2023   °c -2.418    E  Estimated value
2           2022  2022   °c  1.964    E  Estimated value
3           2023  2023   °c  1.964    E  Estimated value
4           2022  2022   °c  2.357    E  Estimated value
...          ...   ...  ...    ...  ...              ...
16179       2023  2023   °c  0.499    E  Estimated value
16180       2022  2022   °c  0.494    E  Estimated value
16181       2023  2023   °c  1.009    E  Estimated value
16182       2022  2022   °c  0.311    E  Estimated value
16183       2023  2023   °c  0.311    E  Estimated value

[16184 rows x 14 columns]>

In [9]:
climate_df.dtypes

Domain Code             str
Domain                  str
Area Code (M49)       int64
Area                    str
Element Code          int64
Element                 str
Months Code           int64
Months                  str
Year Code             int64
Year                  int64
Unit                    str
Value               float64
Flag                    str
Flag Description        str
dtype: object

In [10]:
climate_df.columns

Index(['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code',
       'Element', 'Months Code', 'Months', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description'],
      dtype='str')

#### **duplicates, null values, outliers**

In [11]:
climate_df.duplicated().sum()

np.int64(0)

In [16]:
climate_df.isnull().sum() * 100 / len(climate_df) # calcluates the % missing values

Domain Code         0.000000
Domain              0.000000
Area Code (M49)     0.000000
Area                0.000000
Element Code        0.000000
Element             0.000000
Months Code         0.000000
Months              0.000000
Year Code           0.000000
Year                0.000000
Unit                0.000000
Value               6.043005
Flag                0.000000
Flag Description    0.000000
dtype: float64

Insight: the % of missing values in the 'Value" columnis approx at 6% hence we can drop the missing values, the remedy to this is dropping the missing values

In [17]:
cleaned_climate_df = climate_df.dropna()

In [18]:
cleaned_climate_df.isnull().sum() * 100 / len(cleaned_climate_df) # zero missing values

Domain Code         0.0
Domain              0.0
Area Code (M49)     0.0
Area                0.0
Element Code        0.0
Element             0.0
Months Code         0.0
Months              0.0
Year Code           0.0
Year                0.0
Unit                0.0
Value               0.0
Flag                0.0
Flag Description    0.0
dtype: float64