![alt text](image.png)

![alt text](image-1.png)

![alt text](image-2.png)

![alt text](image-3.png)

![alt text](image-4.png)

# Steps in conducting a hypothesis test: 
- Formulate the Null and Alternative Hypothesis
- Gather evidence(data)
- Calculate the test statistic
- Make a conclusion

## **Using Randomly Generated Data:**

**Problem:**
A Telecom service provider claims that individual customers pay on an average 400 bob per month with standard deviation of 25 bob A random sample of 50 customers bills during a given month is taken with a mean of 250 and standard deviation of 15.

summary:A telecom company claims that customer pay 400 bob a month on average for internet. We take 50 random bills and find the average is 250 bob permonth. Is the company lying?

- Claim: avg = 400
- Based on the sample: 
     - n =50
     - sample mean = 250 
     - sample sd = 15


**Step 1: Formulate the Hypotheses:**
- Null (claim): mean = 400
- Alternative: mean != 400

- note: we are dealing with a *two tailed test* and it is numerical in nature hence the ideal test would be a t-test

#### **Import Necessary Libraries**

In [157]:
import numpy as np 
import pandas as pd
from scipy import stats
from sklearn.datasets import load_iris

#### **Generate/ Simulate the data(evidence/ data)**

In [158]:
np.random.seed(42) # it generates pseudo random numbers = > Mathematical formular (consitency or rather enable reproducability), 42 states that i willbe statring from the 42nd position
bills = np.random.normal(250, 15, 50) # mean -250, sd - 15, n - 50

In [159]:
output =f"We have generated {len(bills)} random bills"
print(output)

We have generated 50 random bills

#### **Sample Statistic:**

In [160]:
mean = bills.mean()
sd = bills.std()
n = len(bills)

output = f"MEAN: {mean:.3f} || Standard Deviation: {sd:.3f} || Sample Size: {n}"
print(output)

MEAN: 246.618 || Standard Deviation: 13.864 || Sample Size: 50

In [161]:
t_stat, p_value = stats.ttest_1samp(bills, 400) # 400 is the claimed parameter value/ mean

output = f"Test Statistic: {t_stat:.3f} || p-value: {p_value:.3f}"
print(output)

Test Statistic: -77.442 || p-value: 0.000

#### **Conclusion:**

*Decision Rule:*
- if p< alpha => Reject the Null Hyp. (statistically significant)
- if p>= alpha => fail to reject the Null Hyp. (not statistically significant)

In [162]:
# assume the level of significance(alpha) = 0.05
alpha = 0.05

output =""
if p_value < 0.05:
    output = "Reject the Null Hypothesis"
else:
    output = "Fail to reject the Null Hypothesis"

print(output)

Reject the Null Hypothesis

<hr>

<hr>

## **Using Real Grouped data:**

data: Iris Dataset


[Iris Dataset Load](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html)

#### **Load Dataset**

In [163]:
iris_data = load_iris() # comes as dict. we access the data using the data key
df = pd.DataFrame(iris_data.data, columns = iris_data.feature_names)
df['species'] = iris_data.target_names[iris_data.target]
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [164]:
type(iris_data.data)

numpy.ndarray

In [165]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [166]:
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [167]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [168]:
df['petal length (cm)'].describe()

count    150.000000
mean       3.758000
std        1.765298
min        1.000000
25%        1.600000
50%        4.350000
75%        5.100000
max        6.900000
Name: petal length (cm), dtype: float64

In [169]:
df.describe(include='object')

/tmp/ipykernel_12139/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       species
count      150
unique       3
top     setosa
freq        50

In [170]:
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

#### **Hypothesis:**

- Null(Ho): setosa petal length == versicolor petal length
- alternative(Ha): setosa petal length != versicolor petal length

- parameter of interest is *mean*
- the groups are independent
- two tailed test
- ideal test statistic here is t-test

#### **Seperate the groups:**

In [171]:
setosa = df[df['species'] == 'setosa']['petal length (cm)']
versicolor = df[df['species'] == 'versicolor']['petal length (cm)']
virginica = df[df['species'] == 'virginica']['petal length (cm)']

#### **Calculate the mean | standard deviation | size**

In [172]:
# length/ size of data sets
len_setosa = len(setosa) 
len_versicolor = len(versicolor)
len_virginica = len(virginica)


# mean
mean_setosa = setosa.mean()
mean_versicolor = versicolor.mean()
mean_virginica = virginica.mean()

# standard deviations
sd_setosa = setosa.std()
sd_versicolor = versicolor.std()
sd_virginica = virginica.std()

output_len = f"LEN** setosa: {len_setosa} |  versicolor: {len_versicolor}  | virginica: {len_virginica}"
output_mean = f"MEAN** setosa: {mean_setosa:.3f} |  versicolor: {mean_versicolor:.3f}  | virginica: {mean_virginica:.3f}"
output_sd = f"SD** setosa: {sd_setosa:.3f} |  versicolor: {sd_versicolor:.3f}  | virginica: {sd_virginica:.3f}"


print("=================================================")
print(output_len)
print(output_mean)
print(output_sd)

print("=================================================")

=================================================
LEN** setosa: 50 |  versicolor: 50  | virginica: 50
MEAN** setosa: 1.462 |  versicolor: 4.260  | virginica: 5.552
SD** setosa: 0.174 |  versicolor: 0.470  | virginica: 0.552
=================================================

In [173]:
setosa.describe()

count    50.000000
mean      1.462000
std       0.173664
min       1.000000
25%       1.400000
50%       1.500000
75%       1.575000
max       1.900000
Name: petal length (cm), dtype: float64

In [174]:
versicolor.describe()

count    50.000000
mean      4.260000
std       0.469911
min       3.000000
25%       4.000000
50%       4.350000
75%       4.600000
max       5.100000
Name: petal length (cm), dtype: float64

In [175]:
virginica.describe()

count    50.000000
mean      5.552000
std       0.551895
min       4.500000
25%       5.100000
50%       5.550000
75%       5.875000
max       6.900000
Name: petal length (cm), dtype: float64

#### **Calculate the Test Statistic**

In [176]:
t_stat, p_value = stats.ttest_ind(setosa, versicolor)

In [177]:
output = f" Test Statistic {t_stat:.4f} | p-value: {p_value:.4f}"
print(output)

 Test Statistic -39.4927 | p-value: 0.0000

#### **Conclusion/ Statistical Significance**

In [178]:
α = 0.05 # alpha

if p_value < α: 
    print("Reject Ho")
else:
    print("fail to reject Ho")

Reject Ho

In [179]:
t_stat, p_value = stats.ttest_ind(versicolor, virginica)
output = f" Test Statistic {t_stat:.4f} | p-value: {p_value:.4f}"
print(output)

α = 0.05 # alpha

if p_value < α: 
    print("Reject Ho")
else:
    print("fail to reject Ho")

 Test Statistic -12.6038 | p-value: 0.0000
Reject Ho

# **Wine_Dataset**

#### **Load Datasets**

In [180]:
red_wine_df = pd.read_csv("data/winequality-red.csv", sep=";")
white_wine_df = pd.read_csv("data/winequality-white.csv", sep=";")

In [181]:
red_wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [182]:
white_wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [183]:
red_wine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [184]:
white_wine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

#### **Hypothesis:**

- Null(Ho): the alcohol levels in red == white
- Alternative(Ha): the alcohol levels in red != white

parameter of interest is the mean

#### **Params:**

In [185]:
def targetParams(df1, df2, targetColumn):
    # mean
    df1_mean = df1[targetColumn].mean()
    df2_mean = df2[targetColumn].mean()

    # standard deviation
    df1_sd = df1[targetColumn].std()
    df2_sd = df2[targetColumn].std()

    # length
    df1_len = len(df1[targetColumn]) 
    df2_len = len(df2[targetColumn]) 

    output_mean = f"MEAN** Red: {df1_mean:.3f} || White: {df2_mean:.3f}"
    output_sd = f"SD** Red: {df1_sd:.3f} || White: {df2_sd:.3f}"
    output_len = f"LEN** Red: {df1_len} || White: {df2_len}"

    print("==========================================")
    print(output_mean)
    print(output_sd)
    print(output_len)
    print("==========================================")

In [186]:
targetParams(red_wine_df,white_wine_df,'alcohol')

==========================================
MEAN** Red: 10.423 || White: 10.514
SD** Red: 1.066 || White: 1.231
LEN** Red: 1599 || White: 4898
==========================================

#### **Calculate the Test Statistic**

In [187]:
len(red_wine_df.columns)

12

In [188]:
def getTstatisticAndConclude(df1, df2, targetColumn):
    t_stat, p_value = stats.ttest_ind(df1[targetColumn], df2[targetColumn])
    output = f"Test Statistic: {t_stat:.4f} | p-value: {p_value:.4f}"
    print(output)
    alpha = 0.05 

    if p_value < alpha:
        print("Reject Ho")

    else:
        print("Fail to reject Ho")

In [189]:
getTstatisticAndConclude(red_wine_df, white_wine_df,'alcohol')

Test Statistic: -2.6585 | p-value: 0.0079
Reject Ho

#### **Targeting Quality**

In [190]:
white_wine_df['quality'].describe()

count    4898.000000
mean        5.877909
std         0.885639
min         3.000000
25%         5.000000
50%         6.000000
75%         6.000000
max         9.000000
Name: quality, dtype: float64

In [191]:
red_wine_df['quality'].describe()

count    1599.000000
mean        5.636023
std         0.807569
min         3.000000
25%         5.000000
50%         6.000000
75%         6.000000
max         8.000000
Name: quality, dtype: float64

In [192]:
targetParams(red_wine_df,white_wine_df,'quality')

==========================================
MEAN** Red: 5.636 || White: 5.878
SD** Red: 0.808 || White: 0.886
LEN** Red: 1599 || White: 4898
==========================================

In [193]:
getTstatisticAndConclude(red_wine_df, white_wine_df,'quality')

Test Statistic: -9.6856 | p-value: 0.0000
Reject Ho

In [194]:
targetParams(red_wine_df,white_wine_df,'fixed acidity')

==========================================
MEAN** Red: 8.320 || White: 6.855
SD** Red: 1.741 || White: 0.844
LEN** Red: 1599 || White: 4898
==========================================

In [195]:
getTstatisticAndConclude(red_wine_df,white_wine_df,'fixed acidity')

Test Statistic: 44.9056 | p-value: 0.0000
Reject Ho